### ISSUE TITLE
Property 'matchAll' does not exist on type 'string'.

### ISSUE THREAD

**Issue by dep-dt** [hensm/fx_cast#102]
As I follow the installation instructions, `npm run build` returns the following error:

```
> node bin/build.js

src/bridge/index.ts:318:43 - error TS2339: Property 'matchAll' does not exist on type 'string'.

318         for (const groups of fileContents.matchAll(REGEX_CAPTION)) {
                                              ~~~~~~~~

Found 1 error.

> pkg@4.4.2
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.13.1-macos-x64   [====================] 100%
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Build failed Error: ENOENT: no such file or directory, stat '/Users/dpeck/Sites/fx_cast/app/selector/mac/build/Build/Products/Release/fx_cast_selector.app'
    at Object.statSync (fs.js:948:3)
    at Object.statSync (/Users/dpeck/Sites/fx_cast/app/node_modules/graceful-fs/polyfills.js:307:34)
    at getStatsSync (/Users/dpeck/Sites/fx_cast/app/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/Users/dpeck/Sites/fx_cast/app/node_modules/fs-extra/lib/util/stat.js:90:33)
    at Object.moveSync (/Users/dpeck/Sites/fx_cast/app/node_modules/fs-extra/lib/move-sync/move-sync.js:14:28)
    at build (/Users/dpeck/Sites/fx_cast/app/bin/build.js:215:12) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/dpeck/Sites/fx_cast/app/selector/mac/build/Build/Products/Release/fx_cast_selector.app'
}
```

**Comment by hensm** [comment]
Oh yep, need to fix that. I think matchAll is just missing from whichever version of the typings are used.

The second error stops the build though, which you can work around by passing `—skipNativeBuilds` to the app build script.

**Comment by hensm** [comment]
705a676 — Fixed
