### ISSUE TITLE
No devices found + weird error logs

### ISSUE THREAD

**Issue by Metalhead33** [hensm/fx_cast#286]
**OS version:** Gentoo Linux, 6.4.15
**Browser version:** 122.0a1 (2013-12-13)
**Extension version:** 0.3.1
**Bridge version:** 0.3.0

**Description**
No receivable devices found (despite me having an Android TV turned on) + the following error message:
```
stderr output from native app fx_cast_bridge: *** WARNING *** The program 'fx_cast_bridge' uses the Apple Bonjour compatibility layer of Avahi.
stderr output from native app fx_cast_bridge: *** WARNING *** Please fix your application to use the native API of Avahi!
stderr output from native app fx_cast_bridge: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
stderr output from native app fx_cast_bridge: *** WARNING *** The program 'fx_cast_bridge' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
stderr output from native app fx_cast_bridge: *** WARNING *** Please fix your application to use the native API of Avahi!
stderr output from native app fx_cast_bridge: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
stderr output from native app fx_cast_bridge: *** WARNING *** The program 'fx_cast_bridge' uses the Apple Bonjour compatibility layer of Avahi.
stderr output from native app fx_cast_bridge: *** WARNING *** Please fix your application to use the native API of Avahi!
stderr output from native app fx_cast_bridge: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
stderr output from native app fx_cast_bridge: *** WARNING *** The program 'fx_cast_bridge' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
stderr output from native app fx_cast_bridge: *** WARNING *** Please fix your application to use the native API of Avahi!
stderr output from native app fx_cast_bridge: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
stderr output from native app fx_cast_bridge: node:events:504
stderr output from native app fx_cast_bridge:       throw er; // Unhandled 'error' event
stderr output from native app fx_cast_bridge:       ^
stderr output from native app fx_cast_bridge: 
stderr output from native app fx_cast_bridge: Error: getaddrinfo -3001
stderr output from native app fx_cast_bridge:     at errnoException (/snapshot/app/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
stderr output from native app fx_cast_bridge:     at getaddrinfo_complete (/snapshot/app/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
stderr output from native app fx_cast_bridge:     at GetAddrInfoReqWrap.oncomplete (/snapshot/app/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
stderr output from native app fx_cast_bridge: Emitted 'error' event on Browser instance at:
stderr output from native app fx_cast_bridge:     at on_resolver_done (/snapshot/app/node_modules/mdns/lib/browser.js:28:14)
stderr output from native app fx_cast_bridge:     at next (/snapshot/app/node_modules/mdns/lib/browser.js:102:7)
stderr output from native app fx_cast_bridge:     at /snapshot/app/node_modules/mdns/lib/resolver_sequence_tasks.js:160:11
stderr output from native app fx_cast_bridge:     at getaddrinfo_complete (/snapshot/app/node_modules/mdns/lib/resolver_sequence_tasks.js:112:7)
stderr output from native app fx_cast_bridge:     at GetAddrInfoReqWrap.oncomplete (/snapshot/app/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9) {
stderr output from native app fx_cast_bridge:   code: -3001,
stderr output from native app fx_cast_bridge:   errno: -3001,
stderr output from native app fx_cast_bridge:   syscall: 'getaddrinfo'
stderr output from native app fx_cast_bridge: } 
```

**Steps to reproduce**
1. Install fx_cast and the fx_cast bridge

**Expected behaviour**
My device being found and no such error messages being generated.

**Comment by Metalhead33** [comment]
Resolved by looking at #280
