### ISSUE TITLE
Bridge Issue: Connection Timed Out

### ISSUE THREAD

**Issue by Emeraldstarmc** [hensm/fx_cast#301]
When trying to cast, the bridge times out. When trying to open bridge, i get this error:
 Unexpected result while probing for avahi: Error: dns service error: service not running
    at supportsInterfaceIndexLocalOnly (C:\snapshot\app\node_modules\mdns\lib\avahi.js:17:12)
    at Object.<anonymous> (C:\snapshot\app\node_modules\mdns\lib\avahi.js:34:20)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1812:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\app\node_modules\mdns\lib\mdns.js:31:19) {
  errorCode: -65563

This is on latest windows, firefox, bridge, and extension

**Comment by Emeraldstarmc** [comment]
Issue was with Bonjour being uninstalled
